services:
  - type: web
    name: dabar-backend
    env: rust
    buildCommand: "chmod +x render-build.sh && ./render-build.sh"
    startCommand: "PATH=$HOME/.local/bin:$PWD/bin:$PWD/bin/node/bin:$PATH ./target/release/dabar-server"
    envVars:
      - key: PORT
        value: "10000"
      - key: YT_DLP_PATH
        value: "./bin/yt-dlp"
      - key: RUST_LOG
        value: "dabar_server=info,tower_http=info"
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dabar-db
          property: connectionString

databases:
  - name: dabar-db
    plan: free
